// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace PubComb {
    
    
    public partial class SitAnywhereFormGTK {
        
        private Gtk.VBox vbox4;
        
        private Gtk.Label lblCredits;
        
        private Gtk.HSeparator hseparator4;
        
        private Gtk.Button cmdSit;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget PubComb.SitAnywhereFormGTK
            this.Name = "PubComb.SitAnywhereFormGTK";
            this.Title = Mono.Unix.Catalog.GetString("SitAnywhereFormGTK");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            // Container child PubComb.SitAnywhereFormGTK.Gtk.Container+ContainerChild
            this.vbox4 = new Gtk.VBox();
            this.vbox4.Name = "vbox4";
            this.vbox4.Spacing = 6;
            // Container child vbox4.Gtk.Box+BoxChild
            this.lblCredits = new Gtk.Label();
            this.lblCredits.Name = "lblCredits";
            this.lblCredits.LabelProp = Mono.Unix.Catalog.GetString("Plugin By LGG.\n\nThanks to PSL for initial concept, and Bilo Parx For logged packet.");
            this.lblCredits.Justify = ((Gtk.Justification)(2));
            this.vbox4.Add(this.lblCredits);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.vbox4[this.lblCredits]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child vbox4.Gtk.Box+BoxChild
            this.hseparator4 = new Gtk.HSeparator();
            this.hseparator4.Name = "hseparator4";
            this.vbox4.Add(this.hseparator4);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox4[this.hseparator4]));
            w2.Position = 1;
            w2.Expand = false;
            w2.Fill = false;
            // Container child vbox4.Gtk.Box+BoxChild
            this.cmdSit = new Gtk.Button();
            this.cmdSit.CanFocus = true;
            this.cmdSit.Name = "cmdSit";
            this.cmdSit.UseUnderline = true;
            this.cmdSit.Label = Mono.Unix.Catalog.GetString("SIT");
            this.vbox4.Add(this.cmdSit);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox4[this.cmdSit]));
            w3.Position = 2;
            w3.Expand = false;
            w3.Fill = false;
            this.Add(this.vbox4);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 427;
            this.DefaultHeight = 300;
            this.Show();
            this.cmdSit.Activated += new System.EventHandler(this.OnCmdSitActivated);
        }
    }
}
