// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace PubComb {
    
    
    public partial class HandicapFormGTK {
        
        private Gtk.VBox vbox4;
        
        private Gtk.Label lblTitle;
        
        private Gtk.CheckButton chkEnabled;
        
        private Gtk.HBox hbox1;
        
        private Gtk.Label label7;
        
        private Gtk.Frame frmDebug;
        
        private Gtk.Alignment GtkAlignment;
        
        private Gtk.ScrolledWindow GtkScrolledWindow;
        
        private Gtk.TextView txtDebug;
        
        private Gtk.Label GtkLabel1;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget PubComb.HandicapFormGTK
            this.Name = "PubComb.HandicapFormGTK";
            this.Title = Mono.Unix.Catalog.GetString("HandicapFormGTK");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            // Container child PubComb.HandicapFormGTK.Gtk.Container+ContainerChild
            this.vbox4 = new Gtk.VBox();
            this.vbox4.Name = "vbox4";
            this.vbox4.Spacing = 6;
            // Container child vbox4.Gtk.Box+BoxChild
            this.lblTitle = new Gtk.Label();
            this.lblTitle.Name = "lblTitle";
            this.lblTitle.LabelProp = Mono.Unix.Catalog.GetString("<b>Handicap</b>\n\nPlugin author unknown\nThanks to Day Oh for binary parsing stuff.");
            this.lblTitle.UseMarkup = true;
            this.lblTitle.Justify = ((Gtk.Justification)(2));
            this.vbox4.Add(this.lblTitle);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.vbox4[this.lblTitle]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child vbox4.Gtk.Box+BoxChild
            this.chkEnabled = new Gtk.CheckButton();
            this.chkEnabled.CanFocus = true;
            this.chkEnabled.Name = "chkEnabled";
            this.chkEnabled.Label = Mono.Unix.Catalog.GetString("Enable quick teleports?");
            this.chkEnabled.DrawIndicator = true;
            this.chkEnabled.UseUnderline = true;
            this.vbox4.Add(this.chkEnabled);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox4[this.chkEnabled]));
            w2.Position = 1;
            w2.Expand = false;
            w2.Fill = false;
            // Container child vbox4.Gtk.Box+BoxChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.label7 = new Gtk.Label();
            this.label7.Name = "label7";
            this.label7.LabelProp = Mono.Unix.Catalog.GetString("<b>Instructions</b>\n\n1. Enable the plugin.\n2. Type <i>handi-</i> in your Second Life client.\n3. In the menu that appears, push \"Help\".");
            this.label7.UseMarkup = true;
            this.label7.Wrap = true;
            this.hbox1.Add(this.label7);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.hbox1[this.label7]));
            w3.Position = 0;
            w3.Expand = false;
            w3.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.frmDebug = new Gtk.Frame();
            this.frmDebug.Name = "frmDebug";
            this.frmDebug.ShadowType = ((Gtk.ShadowType)(0));
            // Container child frmDebug.Gtk.Container+ContainerChild
            this.GtkAlignment = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment.Name = "GtkAlignment";
            this.GtkAlignment.LeftPadding = ((uint)(12));
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            this.GtkScrolledWindow = new Gtk.ScrolledWindow();
            this.GtkScrolledWindow.WidthRequest = 200;
            this.GtkScrolledWindow.HeightRequest = 150;
            this.GtkScrolledWindow.Sensitive = false;
            this.GtkScrolledWindow.Name = "GtkScrolledWindow";
            this.GtkScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
            // Container child GtkScrolledWindow.Gtk.Container+ContainerChild
            this.txtDebug = new Gtk.TextView();
            this.txtDebug.Buffer.Text = "Debug data:\n";
            this.txtDebug.CanFocus = true;
            this.txtDebug.Name = "txtDebug";
            this.GtkScrolledWindow.Add(this.txtDebug);
            this.GtkAlignment.Add(this.GtkScrolledWindow);
            this.frmDebug.Add(this.GtkAlignment);
            this.GtkLabel1 = new Gtk.Label();
            this.GtkLabel1.Name = "GtkLabel1";
            this.GtkLabel1.LabelProp = Mono.Unix.Catalog.GetString("<b>Debug Data</b>");
            this.GtkLabel1.UseMarkup = true;
            this.frmDebug.LabelWidget = this.GtkLabel1;
            this.hbox1.Add(this.frmDebug);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.hbox1[this.frmDebug]));
            w7.Position = 1;
            w7.Expand = false;
            w7.Fill = false;
            this.vbox4.Add(this.hbox1);
            Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.vbox4[this.hbox1]));
            w8.Position = 2;
            w8.Expand = false;
            w8.Fill = false;
            this.Add(this.vbox4);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 509;
            this.DefaultHeight = 300;
            this.Show();
            this.chkEnabled.Clicked += new System.EventHandler(this.OnChkEnabledClicked);
        }
    }
}
