// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace PubComb {
    
    
    public partial class ProfileFunFormGTK {
        
        private Gtk.VBox vbox3;
        
        private Gtk.Label lblTitle;
        
        private Gtk.HSeparator hseparator4;
        
        private Gtk.CheckButton chkEnableLocationTracking;
        
        private Gtk.HBox hbox1;
        
        private Gtk.Label lblURLBase;
        
        private Gtk.Entry txtURLBase;
        
        private Gtk.Frame frameProfile;
        
        private Gtk.Alignment GtkAlignment;
        
        private Gtk.Table table2;
        
        private Gtk.ScrolledWindow GtkScrolledWindow;
        
        private Gtk.TextView txtAbout;
        
        private Gtk.Label lbl2LImage;
        
        private Gtk.Label lblAbout;
        
        private Gtk.Label lblWebsite;
        
        private Gtk.Entry txtImage;
        
        private Gtk.Entry txtWebsite;
        
        private Gtk.Label lblSLProfile;
        
        private Gtk.Frame frameRL;
        
        private Gtk.Alignment GtkAlignment1;
        
        private Gtk.Table table3;
        
        private Gtk.ScrolledWindow GtkScrolledWindow1;
        
        private Gtk.TextView txtRLAbout;
        
        private Gtk.Label lblRLAbout;
        
        private Gtk.Label lblRLImage;
        
        private Gtk.Entry txtRLImage;
        
        private Gtk.Label lblFLProfile;
        
        private Gtk.Button cmdSave;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget PubComb.ProfileFunFormGTK
            this.Name = "PubComb.ProfileFunFormGTK";
            this.Title = Mono.Unix.Catalog.GetString("ProfileFunFormGTK");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            // Container child PubComb.ProfileFunFormGTK.Gtk.Container+ContainerChild
            this.vbox3 = new Gtk.VBox();
            this.vbox3.Name = "vbox3";
            this.vbox3.Spacing = 6;
            // Container child vbox3.Gtk.Box+BoxChild
            this.lblTitle = new Gtk.Label();
            this.lblTitle.Name = "lblTitle";
            this.lblTitle.LabelProp = Mono.Unix.Catalog.GetString("Profile Fun\n\nPlugin by LGG");
            this.lblTitle.Justify = ((Gtk.Justification)(2));
            this.vbox3.Add(this.lblTitle);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.vbox3[this.lblTitle]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.hseparator4 = new Gtk.HSeparator();
            this.hseparator4.Name = "hseparator4";
            this.vbox3.Add(this.hseparator4);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox3[this.hseparator4]));
            w2.Position = 1;
            w2.Expand = false;
            w2.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.chkEnableLocationTracking = new Gtk.CheckButton();
            this.chkEnableLocationTracking.CanFocus = true;
            this.chkEnableLocationTracking.Name = "chkEnableLocationTracking";
            this.chkEnableLocationTracking.Label = Mono.Unix.Catalog.GetString("Enable autofill of website URL with location URL?");
            this.chkEnableLocationTracking.DrawIndicator = true;
            this.chkEnableLocationTracking.UseUnderline = true;
            this.vbox3.Add(this.chkEnableLocationTracking);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox3[this.chkEnableLocationTracking]));
            w3.Position = 2;
            w3.Expand = false;
            w3.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.lblURLBase = new Gtk.Label();
            this.lblURLBase.Name = "lblURLBase";
            this.lblURLBase.LabelProp = Mono.Unix.Catalog.GetString("URL Base:");
            this.hbox1.Add(this.lblURLBase);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.hbox1[this.lblURLBase]));
            w4.Position = 0;
            w4.Expand = false;
            w4.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.txtURLBase = new Gtk.Entry();
            this.txtURLBase.CanFocus = true;
            this.txtURLBase.Name = "txtURLBase";
            this.txtURLBase.Text = Mono.Unix.Catalog.GetString("http://the-diy-life.com/super1337hax/LGGRedirect.php?loc=");
            this.txtURLBase.IsEditable = true;
            this.txtURLBase.InvisibleChar = '●';
            this.hbox1.Add(this.txtURLBase);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.hbox1[this.txtURLBase]));
            w5.Position = 1;
            this.vbox3.Add(this.hbox1);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.vbox3[this.hbox1]));
            w6.Position = 3;
            w6.Expand = false;
            w6.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.frameProfile = new Gtk.Frame();
            this.frameProfile.Name = "frameProfile";
            this.frameProfile.ShadowType = ((Gtk.ShadowType)(0));
            // Container child frameProfile.Gtk.Container+ContainerChild
            this.GtkAlignment = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment.Name = "GtkAlignment";
            this.GtkAlignment.LeftPadding = ((uint)(12));
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            this.table2 = new Gtk.Table(((uint)(3)), ((uint)(2)), false);
            this.table2.Name = "table2";
            this.table2.RowSpacing = ((uint)(6));
            this.table2.ColumnSpacing = ((uint)(6));
            // Container child table2.Gtk.Table+TableChild
            this.GtkScrolledWindow = new Gtk.ScrolledWindow();
            this.GtkScrolledWindow.Name = "GtkScrolledWindow";
            this.GtkScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
            // Container child GtkScrolledWindow.Gtk.Container+ContainerChild
            this.txtAbout = new Gtk.TextView();
            this.txtAbout.CanFocus = true;
            this.txtAbout.Name = "txtAbout";
            this.GtkScrolledWindow.Add(this.txtAbout);
            this.table2.Add(this.GtkScrolledWindow);
            Gtk.Table.TableChild w8 = ((Gtk.Table.TableChild)(this.table2[this.GtkScrolledWindow]));
            w8.TopAttach = ((uint)(1));
            w8.BottomAttach = ((uint)(2));
            w8.LeftAttach = ((uint)(1));
            w8.RightAttach = ((uint)(2));
            w8.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.lbl2LImage = new Gtk.Label();
            this.lbl2LImage.Name = "lbl2LImage";
            this.lbl2LImage.LabelProp = Mono.Unix.Catalog.GetString("Image ID:");
            this.table2.Add(this.lbl2LImage);
            Gtk.Table.TableChild w9 = ((Gtk.Table.TableChild)(this.table2[this.lbl2LImage]));
            w9.XOptions = ((Gtk.AttachOptions)(4));
            w9.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.lblAbout = new Gtk.Label();
            this.lblAbout.Name = "lblAbout";
            this.lblAbout.LabelProp = Mono.Unix.Catalog.GetString("About:");
            this.table2.Add(this.lblAbout);
            Gtk.Table.TableChild w10 = ((Gtk.Table.TableChild)(this.table2[this.lblAbout]));
            w10.TopAttach = ((uint)(1));
            w10.BottomAttach = ((uint)(2));
            w10.XOptions = ((Gtk.AttachOptions)(4));
            w10.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.lblWebsite = new Gtk.Label();
            this.lblWebsite.Name = "lblWebsite";
            this.lblWebsite.LabelProp = Mono.Unix.Catalog.GetString("Website:");
            this.table2.Add(this.lblWebsite);
            Gtk.Table.TableChild w11 = ((Gtk.Table.TableChild)(this.table2[this.lblWebsite]));
            w11.TopAttach = ((uint)(2));
            w11.BottomAttach = ((uint)(3));
            w11.XOptions = ((Gtk.AttachOptions)(4));
            w11.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.txtImage = new Gtk.Entry();
            this.txtImage.CanFocus = true;
            this.txtImage.Name = "txtImage";
            this.txtImage.IsEditable = true;
            this.txtImage.InvisibleChar = '●';
            this.table2.Add(this.txtImage);
            Gtk.Table.TableChild w12 = ((Gtk.Table.TableChild)(this.table2[this.txtImage]));
            w12.LeftAttach = ((uint)(1));
            w12.RightAttach = ((uint)(2));
            w12.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.txtWebsite = new Gtk.Entry();
            this.txtWebsite.CanFocus = true;
            this.txtWebsite.Name = "txtWebsite";
            this.txtWebsite.IsEditable = true;
            this.txtWebsite.InvisibleChar = '●';
            this.table2.Add(this.txtWebsite);
            Gtk.Table.TableChild w13 = ((Gtk.Table.TableChild)(this.table2[this.txtWebsite]));
            w13.TopAttach = ((uint)(2));
            w13.BottomAttach = ((uint)(3));
            w13.LeftAttach = ((uint)(1));
            w13.RightAttach = ((uint)(2));
            w13.YOptions = ((Gtk.AttachOptions)(4));
            this.GtkAlignment.Add(this.table2);
            this.frameProfile.Add(this.GtkAlignment);
            this.lblSLProfile = new Gtk.Label();
            this.lblSLProfile.Name = "lblSLProfile";
            this.lblSLProfile.LabelProp = Mono.Unix.Catalog.GetString("<b>Second Life Profile</b>");
            this.lblSLProfile.UseMarkup = true;
            this.frameProfile.LabelWidget = this.lblSLProfile;
            this.vbox3.Add(this.frameProfile);
            Gtk.Box.BoxChild w16 = ((Gtk.Box.BoxChild)(this.vbox3[this.frameProfile]));
            w16.Position = 4;
            w16.Expand = false;
            w16.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.frameRL = new Gtk.Frame();
            this.frameRL.Name = "frameRL";
            this.frameRL.ShadowType = ((Gtk.ShadowType)(0));
            // Container child frameRL.Gtk.Container+ContainerChild
            this.GtkAlignment1 = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment1.Name = "GtkAlignment1";
            this.GtkAlignment1.LeftPadding = ((uint)(12));
            // Container child GtkAlignment1.Gtk.Container+ContainerChild
            this.table3 = new Gtk.Table(((uint)(2)), ((uint)(2)), false);
            this.table3.Name = "table3";
            this.table3.RowSpacing = ((uint)(6));
            this.table3.ColumnSpacing = ((uint)(6));
            // Container child table3.Gtk.Table+TableChild
            this.GtkScrolledWindow1 = new Gtk.ScrolledWindow();
            this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
            this.GtkScrolledWindow1.ShadowType = ((Gtk.ShadowType)(1));
            // Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
            this.txtRLAbout = new Gtk.TextView();
            this.txtRLAbout.CanFocus = true;
            this.txtRLAbout.Name = "txtRLAbout";
            this.GtkScrolledWindow1.Add(this.txtRLAbout);
            this.table3.Add(this.GtkScrolledWindow1);
            Gtk.Table.TableChild w18 = ((Gtk.Table.TableChild)(this.table3[this.GtkScrolledWindow1]));
            w18.TopAttach = ((uint)(1));
            w18.BottomAttach = ((uint)(2));
            w18.LeftAttach = ((uint)(1));
            w18.RightAttach = ((uint)(2));
            w18.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.lblRLAbout = new Gtk.Label();
            this.lblRLAbout.Name = "lblRLAbout";
            this.lblRLAbout.LabelProp = Mono.Unix.Catalog.GetString("About:");
            this.table3.Add(this.lblRLAbout);
            Gtk.Table.TableChild w19 = ((Gtk.Table.TableChild)(this.table3[this.lblRLAbout]));
            w19.TopAttach = ((uint)(1));
            w19.BottomAttach = ((uint)(2));
            w19.XOptions = ((Gtk.AttachOptions)(4));
            w19.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.lblRLImage = new Gtk.Label();
            this.lblRLImage.Name = "lblRLImage";
            this.lblRLImage.LabelProp = Mono.Unix.Catalog.GetString("Image ID:");
            this.table3.Add(this.lblRLImage);
            Gtk.Table.TableChild w20 = ((Gtk.Table.TableChild)(this.table3[this.lblRLImage]));
            w20.XOptions = ((Gtk.AttachOptions)(4));
            w20.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.txtRLImage = new Gtk.Entry();
            this.txtRLImage.CanFocus = true;
            this.txtRLImage.Name = "txtRLImage";
            this.txtRLImage.IsEditable = true;
            this.txtRLImage.InvisibleChar = '●';
            this.table3.Add(this.txtRLImage);
            Gtk.Table.TableChild w21 = ((Gtk.Table.TableChild)(this.table3[this.txtRLImage]));
            w21.LeftAttach = ((uint)(1));
            w21.RightAttach = ((uint)(2));
            w21.YOptions = ((Gtk.AttachOptions)(4));
            this.GtkAlignment1.Add(this.table3);
            this.frameRL.Add(this.GtkAlignment1);
            this.lblFLProfile = new Gtk.Label();
            this.lblFLProfile.Name = "lblFLProfile";
            this.lblFLProfile.LabelProp = Mono.Unix.Catalog.GetString("<b>First Life Tab</b>");
            this.lblFLProfile.UseMarkup = true;
            this.frameRL.LabelWidget = this.lblFLProfile;
            this.vbox3.Add(this.frameRL);
            Gtk.Box.BoxChild w24 = ((Gtk.Box.BoxChild)(this.vbox3[this.frameRL]));
            w24.Position = 5;
            w24.Expand = false;
            w24.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.cmdSave = new Gtk.Button();
            this.cmdSave.CanFocus = true;
            this.cmdSave.Name = "cmdSave";
            this.cmdSave.UseUnderline = true;
            this.cmdSave.Label = Mono.Unix.Catalog.GetString("Update Profile");
            this.vbox3.Add(this.cmdSave);
            Gtk.Box.BoxChild w25 = ((Gtk.Box.BoxChild)(this.vbox3[this.cmdSave]));
            w25.Position = 6;
            w25.Expand = false;
            w25.Fill = false;
            this.Add(this.vbox3);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 400;
            this.DefaultHeight = 521;
            this.Show();
            this.chkEnableLocationTracking.Clicked += new System.EventHandler(this.OnChkEnableLocationTrackingClicked);
            this.cmdSave.Activated += new System.EventHandler(this.OnCmdSaveActivated);
        }
    }
}
