// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace PubComb {
    
    
    public partial class PAnimFormGTK {
        
        private Gtk.VBox vbox1;
        
        private Gtk.Label lblTitle;
        
        private Gtk.HSeparator hseparator2;
        
        private Gtk.Frame frame1;
        
        private Gtk.Alignment GtkAlignment;
        
        private Gtk.ComboBox cboPLevel;
        
        private Gtk.Label lblCombo;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget PubComb.PAnimFormGTK
            this.Name = "PubComb.PAnimFormGTK";
            this.Title = Mono.Unix.Catalog.GetString("ProtAnim - By LordGregGreg Back");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            // Container child PubComb.PAnimFormGTK.Gtk.Container+ContainerChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            this.lblTitle = new Gtk.Label();
            this.lblTitle.Name = "lblTitle";
            this.lblTitle.LabelProp = Mono.Unix.Catalog.GetString("<b>Protective AO</b> (Keeps you from crashing)\n\nPlugin By LGG.\n\n<b>Special thanks:</b>\nThe Animation Specialist, Zwagoth Klaar himself!\nAll Others Who Helped Me With This :)");
            this.lblTitle.UseMarkup = true;
            this.lblTitle.Justify = ((Gtk.Justification)(2));
            this.vbox1.Add(this.lblTitle);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.vbox1[this.lblTitle]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hseparator2 = new Gtk.HSeparator();
            this.hseparator2.Name = "hseparator2";
            this.vbox1.Add(this.hseparator2);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox1[this.hseparator2]));
            w2.Position = 1;
            w2.Expand = false;
            w2.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.frame1 = new Gtk.Frame();
            this.frame1.Name = "frame1";
            this.frame1.ShadowType = ((Gtk.ShadowType)(0));
            // Container child frame1.Gtk.Container+ContainerChild
            this.GtkAlignment = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment.Name = "GtkAlignment";
            this.GtkAlignment.LeftPadding = ((uint)(12));
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            this.cboPLevel = Gtk.ComboBox.NewText();
            this.cboPLevel.AppendText(Mono.Unix.Catalog.GetString("Block All Animations\r"));
            this.cboPLevel.AppendText(Mono.Unix.Catalog.GetString("Block All But Linden Animations\r"));
            this.cboPLevel.AppendText(Mono.Unix.Catalog.GetString("Block Only Animations With New Stuff\r"));
            this.cboPLevel.AppendText(Mono.Unix.Catalog.GetString("Block Only Animations With Crazy Stuff\r"));
            this.cboPLevel.AppendText(Mono.Unix.Catalog.GetString("Block Only Animations With Very Evil Stuff\r"));
            this.cboPLevel.AppendText(Mono.Unix.Catalog.GetString("Block Only Animations That Can Crash You\r"));
            this.cboPLevel.AppendText(Mono.Unix.Catalog.GetString("Block Only Animations That Are Known To Crash You"));
            this.cboPLevel.Name = "cboPLevel";
            this.cboPLevel.Active = 6;
            this.GtkAlignment.Add(this.cboPLevel);
            this.frame1.Add(this.GtkAlignment);
            this.lblCombo = new Gtk.Label();
            this.lblCombo.Name = "lblCombo";
            this.lblCombo.LabelProp = Mono.Unix.Catalog.GetString("<b>Protection Level:</b>");
            this.lblCombo.UseMarkup = true;
            this.frame1.LabelWidget = this.lblCombo;
            this.vbox1.Add(this.frame1);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.vbox1[this.frame1]));
            w5.Position = 2;
            w5.Expand = false;
            w5.Fill = false;
            this.Add(this.vbox1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 400;
            this.DefaultHeight = 300;
            this.Show();
        }
    }
}
