// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace PubComb {
    
    
    public partial class CliIntFormGTK {
        
        private Gtk.VBox vbox1;
        
        private Gtk.Label lblTitle;
        
        private Gtk.Label txtAbout;
        
        private Gtk.HSeparator hseparator1;
        
        private Gtk.CheckButton chkEnabled;
        
        private Gtk.CheckButton chkTempOnRez;
        
        private Gtk.HSeparator hseparator2;
        
        private Gtk.Table table1;
        
        private Gtk.Label lblInventory;
        
        private Gtk.Entry txtInventory;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget PubComb.CliIntFormGTK
            this.Name = "PubComb.CliIntFormGTK";
            this.Title = Mono.Unix.Catalog.GetString("CliIntFormGTK");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            // Container child PubComb.CliIntFormGTK.Gtk.Container+ContainerChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            this.lblTitle = new Gtk.Label();
            this.lblTitle.Name = "lblTitle";
            this.lblTitle.Xpad = 2;
            this.lblTitle.Ypad = 8;
            this.lblTitle.LabelProp = Mono.Unix.Catalog.GetString("Client Interceptors");
            this.lblTitle.UseMarkup = true;
            this.vbox1.Add(this.lblTitle);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.vbox1[this.lblTitle]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.txtAbout = new Gtk.Label();
            this.txtAbout.Name = "txtAbout";
            this.txtAbout.LabelProp = Mono.Unix.Catalog.GetString("Plugin by Gregory Maurer, Modified by LGG.");
            this.txtAbout.Justify = ((Gtk.Justification)(2));
            this.vbox1.Add(this.txtAbout);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox1[this.txtAbout]));
            w2.Position = 1;
            w2.Expand = false;
            w2.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hseparator1 = new Gtk.HSeparator();
            this.hseparator1.Name = "hseparator1";
            this.vbox1.Add(this.hseparator1);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox1[this.hseparator1]));
            w3.Position = 2;
            w3.Expand = false;
            w3.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.chkEnabled = new Gtk.CheckButton();
            this.chkEnabled.CanFocus = true;
            this.chkEnabled.Name = "chkEnabled";
            this.chkEnabled.Label = Mono.Unix.Catalog.GetString("Check to enable the rezzing of interceptors from your inventory.");
            this.chkEnabled.DrawIndicator = true;
            this.chkEnabled.UseUnderline = true;
            this.vbox1.Add(this.chkEnabled);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.vbox1[this.chkEnabled]));
            w4.Position = 3;
            w4.Expand = false;
            w4.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.chkTempOnRez = new Gtk.CheckButton();
            this.chkTempOnRez.CanFocus = true;
            this.chkTempOnRez.Name = "chkTempOnRez";
            this.chkTempOnRez.Label = Mono.Unix.Catalog.GetString("Rez as a temporary object? (Deletes after 60s)");
            this.chkTempOnRez.Active = true;
            this.chkTempOnRez.DrawIndicator = true;
            this.chkTempOnRez.UseUnderline = true;
            this.vbox1.Add(this.chkTempOnRez);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.vbox1[this.chkTempOnRez]));
            w5.Position = 4;
            w5.Expand = false;
            w5.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hseparator2 = new Gtk.HSeparator();
            this.hseparator2.Name = "hseparator2";
            this.vbox1.Add(this.hseparator2);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.vbox1[this.hseparator2]));
            w6.Position = 5;
            w6.Expand = false;
            w6.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.table1 = new Gtk.Table(((uint)(1)), ((uint)(2)), false);
            this.table1.Name = "table1";
            this.table1.RowSpacing = ((uint)(6));
            this.table1.ColumnSpacing = ((uint)(6));
            // Container child table1.Gtk.Table+TableChild
            this.lblInventory = new Gtk.Label();
            this.lblInventory.Name = "lblInventory";
            this.lblInventory.LabelProp = Mono.Unix.Catalog.GetString("Path to Objects \n  ex:  test/RezzedIntercept\n\nWhere test is a folder in the root (with few items in it)  and RezzedIntercept is the object to rez.");
            this.lblInventory.Wrap = true;
            this.table1.Add(this.lblInventory);
            Gtk.Table.TableChild w7 = ((Gtk.Table.TableChild)(this.table1[this.lblInventory]));
            w7.XOptions = ((Gtk.AttachOptions)(4));
            w7.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.txtInventory = new Gtk.Entry();
            this.txtInventory.CanFocus = true;
            this.txtInventory.Name = "txtInventory";
            this.txtInventory.IsEditable = true;
            this.txtInventory.InvisibleChar = '●';
            this.table1.Add(this.txtInventory);
            Gtk.Table.TableChild w8 = ((Gtk.Table.TableChild)(this.table1[this.txtInventory]));
            w8.LeftAttach = ((uint)(1));
            w8.RightAttach = ((uint)(2));
            w8.YOptions = ((Gtk.AttachOptions)(4));
            this.vbox1.Add(this.table1);
            Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.vbox1[this.table1]));
            w9.Position = 6;
            w9.Expand = false;
            w9.Fill = false;
            this.Add(this.vbox1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 627;
            this.DefaultHeight = 354;
            this.Show();
            this.chkEnabled.Clicked += new System.EventHandler(this.OnChkEnableClicked);
            this.txtInventory.EditingDone += new System.EventHandler(this.OnTxtInventoryEditingDone);
        }
    }
}
