// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace PubComb {
    
    
    public partial class SitBlockFormGTK {
        
        private Gtk.VBox vbox3;
        
        private Gtk.Label lblTitle;
        
        private Gtk.HSeparator hseparator2;
        
        private Gtk.CheckButton chkEnabled;
        
        private Gtk.CheckButton chkMineOnly;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget PubComb.SitBlockFormGTK
            this.Name = "PubComb.SitBlockFormGTK";
            this.Title = Mono.Unix.Catalog.GetString("SitBlockFormGTK");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            // Container child PubComb.SitBlockFormGTK.Gtk.Container+ContainerChild
            this.vbox3 = new Gtk.VBox();
            this.vbox3.Name = "vbox3";
            this.vbox3.Spacing = 6;
            // Container child vbox3.Gtk.Box+BoxChild
            this.lblTitle = new Gtk.Label();
            this.lblTitle.Name = "lblTitle";
            this.lblTitle.LabelProp = Mono.Unix.Catalog.GetString("Plugin by LordGregGreg\n\nNOTE: Very beta.");
            this.lblTitle.Justify = ((Gtk.Justification)(2));
            this.vbox3.Add(this.lblTitle);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.vbox3[this.lblTitle]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.hseparator2 = new Gtk.HSeparator();
            this.hseparator2.Name = "hseparator2";
            this.vbox3.Add(this.hseparator2);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox3[this.hseparator2]));
            w2.Position = 1;
            w2.Expand = false;
            w2.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.chkEnabled = new Gtk.CheckButton();
            this.chkEnabled.CanFocus = true;
            this.chkEnabled.Name = "chkEnabled";
            this.chkEnabled.Label = Mono.Unix.Catalog.GetString("Block me from sitting on ANYTHING (such as orbiters!)");
            this.chkEnabled.DrawIndicator = true;
            this.chkEnabled.UseUnderline = true;
            this.vbox3.Add(this.chkEnabled);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox3[this.chkEnabled]));
            w3.Position = 2;
            w3.Expand = false;
            w3.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.chkMineOnly = new Gtk.CheckButton();
            this.chkMineOnly.Sensitive = false;
            this.chkMineOnly.CanFocus = true;
            this.chkMineOnly.Name = "chkMineOnly";
            this.chkMineOnly.Label = Mono.Unix.Catalog.GetString(".. but only for objects I don't own. (Not ready yet)");
            this.chkMineOnly.DrawIndicator = true;
            this.chkMineOnly.UseUnderline = true;
            this.vbox3.Add(this.chkMineOnly);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.vbox3[this.chkMineOnly]));
            w4.PackType = ((Gtk.PackType)(1));
            w4.Position = 3;
            w4.Expand = false;
            w4.Fill = false;
            this.Add(this.vbox3);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 400;
            this.DefaultHeight = 300;
            this.Show();
            this.chkEnabled.Toggled += new System.EventHandler(this.OnChkEnabledToggled);
        }
    }
}
