// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace PubComb {
    
    
    public partial class frmMain {
        
        private Gtk.Notebook tabControl1;
        
        private Gtk.Fixed fixed1;
        
        private Gtk.Label label1;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget PubComb.frmMain
            this.Name = "PubComb.frmMain";
            this.Title = Mono.Unix.Catalog.GetString("Pubcomb Config");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            // Container child PubComb.frmMain.Gtk.Container+ContainerChild
            this.tabControl1 = new Gtk.Notebook();
            this.tabControl1.CanFocus = true;
            this.tabControl1.Name = "tabControl1";
            this.tabControl1.CurrentPage = 0;
            // Container child tabControl1.Gtk.Notebook+NotebookChild
            this.fixed1 = new Gtk.Fixed();
            this.fixed1.Name = "fixed1";
            this.fixed1.HasWindow = false;
            this.tabControl1.Add(this.fixed1);
            // Notebook tab
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.LabelProp = Mono.Unix.Catalog.GetString("page1");
            this.tabControl1.SetTabLabel(this.fixed1, this.label1);
            this.label1.ShowAll();
            this.Add(this.tabControl1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 599;
            this.DefaultHeight = 300;
            this.Show();
        }
    }
}
