// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace PubComb {
    
    
    public partial class CinderellaFormGTK {
        
        private Gtk.UIManager UIManager;
        
        private Gtk.Action cmdOpen;
        
        private Gtk.Action cmdSave;
        
        private Gtk.Action cmdAbout;
        
        private Gtk.VBox vbox4;
        
        private Gtk.Label lblTitle;
        
        private Gtk.HSeparator hseparator2;
        
        private Gtk.Toolbar toolbar1;
        
        private Gtk.Image selImage;
        
        private Gtk.HSeparator hseparator3;
        
        private Gtk.Frame framPerms;
        
        private Gtk.Alignment GtkAlignment3;
        
        private Gtk.VBox vbox5;
        
        private Gtk.HBox hbox2;
        
        private Gtk.CheckButton chkCopy;
        
        private Gtk.CheckButton chkModify;
        
        private Gtk.CheckButton chkTransfer;
        
        private Gtk.CheckButton chkLossLess;
        
        private Gtk.Label lblPermissions;
        
        private Gtk.Statusbar StatusBar;
        
        private Gtk.ProgressBar pbLoadStatus;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget PubComb.CinderellaFormGTK
            this.UIManager = new Gtk.UIManager();
            Gtk.ActionGroup w1 = new Gtk.ActionGroup("Default");
            this.cmdOpen = new Gtk.Action("cmdOpen", Mono.Unix.Catalog.GetString("_Open"), null, "gtk-open");
            this.cmdOpen.ShortLabel = Mono.Unix.Catalog.GetString("_Open");
            w1.Add(this.cmdOpen, null);
            this.cmdSave = new Gtk.Action("cmdSave", Mono.Unix.Catalog.GetString("_Save to SL"), null, "gtk-save");
            this.cmdSave.ShortLabel = Mono.Unix.Catalog.GetString("_Save to SL");
            w1.Add(this.cmdSave, null);
            this.cmdAbout = new Gtk.Action("cmdAbout", Mono.Unix.Catalog.GetString("_About"), null, "gtk-help");
            this.cmdAbout.ShortLabel = Mono.Unix.Catalog.GetString("_About");
            w1.Add(this.cmdAbout, null);
            this.UIManager.InsertActionGroup(w1, 0);
            this.AddAccelGroup(this.UIManager.AccelGroup);
            this.Name = "PubComb.CinderellaFormGTK";
            this.Title = Mono.Unix.Catalog.GetString("CinderellaFormGTK");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            // Container child PubComb.CinderellaFormGTK.Gtk.Container+ContainerChild
            this.vbox4 = new Gtk.VBox();
            this.vbox4.Name = "vbox4";
            this.vbox4.Spacing = 6;
            // Container child vbox4.Gtk.Box+BoxChild
            this.lblTitle = new Gtk.Label();
            this.lblTitle.Name = "lblTitle";
            this.lblTitle.LabelProp = Mono.Unix.Catalog.GetString("Plugin by LGG.\n\nInterface completely redone by N3X15.");
            this.lblTitle.Justify = ((Gtk.Justification)(2));
            this.vbox4.Add(this.lblTitle);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox4[this.lblTitle]));
            w2.Position = 0;
            w2.Expand = false;
            w2.Fill = false;
            // Container child vbox4.Gtk.Box+BoxChild
            this.hseparator2 = new Gtk.HSeparator();
            this.hseparator2.Name = "hseparator2";
            this.vbox4.Add(this.hseparator2);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox4[this.hseparator2]));
            w3.Position = 1;
            w3.Expand = false;
            w3.Fill = false;
            // Container child vbox4.Gtk.Box+BoxChild
            this.UIManager.AddUiFromString("<ui><toolbar name='toolbar1'><toolitem name='cmdOpen' action='cmdOpen'/><toolitem name='cmdSave' action='cmdSave'/><toolitem name='cmdAbout' action='cmdAbout'/></toolbar></ui>");
            this.toolbar1 = ((Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar1")));
            this.toolbar1.Name = "toolbar1";
            this.toolbar1.ShowArrow = false;
            this.toolbar1.ToolbarStyle = ((Gtk.ToolbarStyle)(0));
            this.toolbar1.IconSize = ((Gtk.IconSize)(3));
            this.vbox4.Add(this.toolbar1);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.vbox4[this.toolbar1]));
            w4.Position = 2;
            w4.Expand = false;
            w4.Fill = false;
            // Container child vbox4.Gtk.Box+BoxChild
            this.selImage = new Gtk.Image();
            this.selImage.Name = "selImage";
            this.selImage.Pixbuf = Stetic.IconLoader.LoadIcon(this, "stock_dialog-error", Gtk.IconSize.Menu, 16);
            this.vbox4.Add(this.selImage);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.vbox4[this.selImage]));
            w5.Position = 3;
            w5.Expand = false;
            w5.Fill = false;
            // Container child vbox4.Gtk.Box+BoxChild
            this.hseparator3 = new Gtk.HSeparator();
            this.hseparator3.Name = "hseparator3";
            this.vbox4.Add(this.hseparator3);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.vbox4[this.hseparator3]));
            w6.Position = 4;
            w6.Expand = false;
            w6.Fill = false;
            // Container child vbox4.Gtk.Box+BoxChild
            this.framPerms = new Gtk.Frame();
            this.framPerms.Name = "framPerms";
            this.framPerms.ShadowType = ((Gtk.ShadowType)(0));
            // Container child framPerms.Gtk.Container+ContainerChild
            this.GtkAlignment3 = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment3.Name = "GtkAlignment3";
            this.GtkAlignment3.LeftPadding = ((uint)(12));
            // Container child GtkAlignment3.Gtk.Container+ContainerChild
            this.vbox5 = new Gtk.VBox();
            this.vbox5.Name = "vbox5";
            this.vbox5.Spacing = 6;
            // Container child vbox5.Gtk.Box+BoxChild
            this.hbox2 = new Gtk.HBox();
            this.hbox2.Name = "hbox2";
            this.hbox2.Spacing = 6;
            // Container child hbox2.Gtk.Box+BoxChild
            this.chkCopy = new Gtk.CheckButton();
            this.chkCopy.CanFocus = true;
            this.chkCopy.Name = "chkCopy";
            this.chkCopy.Label = Mono.Unix.Catalog.GetString("_Copy");
            this.chkCopy.Active = true;
            this.chkCopy.DrawIndicator = true;
            this.chkCopy.UseUnderline = true;
            this.hbox2.Add(this.chkCopy);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.hbox2[this.chkCopy]));
            w7.Position = 0;
            // Container child hbox2.Gtk.Box+BoxChild
            this.chkModify = new Gtk.CheckButton();
            this.chkModify.CanFocus = true;
            this.chkModify.Name = "chkModify";
            this.chkModify.Label = Mono.Unix.Catalog.GetString("_Mod");
            this.chkModify.Active = true;
            this.chkModify.DrawIndicator = true;
            this.chkModify.UseUnderline = true;
            this.hbox2.Add(this.chkModify);
            Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.hbox2[this.chkModify]));
            w8.Position = 1;
            // Container child hbox2.Gtk.Box+BoxChild
            this.chkTransfer = new Gtk.CheckButton();
            this.chkTransfer.CanFocus = true;
            this.chkTransfer.Name = "chkTransfer";
            this.chkTransfer.Label = Mono.Unix.Catalog.GetString("Transfer");
            this.chkTransfer.Active = true;
            this.chkTransfer.DrawIndicator = true;
            this.chkTransfer.UseUnderline = true;
            this.hbox2.Add(this.chkTransfer);
            Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.hbox2[this.chkTransfer]));
            w9.Position = 2;
            this.vbox5.Add(this.hbox2);
            Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.vbox5[this.hbox2]));
            w10.Position = 0;
            w10.Expand = false;
            w10.Fill = false;
            // Container child vbox5.Gtk.Box+BoxChild
            this.chkLossLess = new Gtk.CheckButton();
            this.chkLossLess.CanFocus = true;
            this.chkLossLess.Name = "chkLossLess";
            this.chkLossLess.Label = Mono.Unix.Catalog.GetString("Store using lossless compression.");
            this.chkLossLess.Active = true;
            this.chkLossLess.DrawIndicator = true;
            this.chkLossLess.UseUnderline = true;
            this.vbox5.Add(this.chkLossLess);
            Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(this.vbox5[this.chkLossLess]));
            w11.Position = 1;
            w11.Expand = false;
            w11.Fill = false;
            this.GtkAlignment3.Add(this.vbox5);
            this.framPerms.Add(this.GtkAlignment3);
            this.lblPermissions = new Gtk.Label();
            this.lblPermissions.Name = "lblPermissions";
            this.lblPermissions.LabelProp = Mono.Unix.Catalog.GetString("<b>Permissions and Upload Settings</b>");
            this.lblPermissions.UseMarkup = true;
            this.framPerms.LabelWidget = this.lblPermissions;
            this.vbox4.Add(this.framPerms);
            Gtk.Box.BoxChild w14 = ((Gtk.Box.BoxChild)(this.vbox4[this.framPerms]));
            w14.Position = 5;
            w14.Expand = false;
            w14.Fill = false;
            // Container child vbox4.Gtk.Box+BoxChild
            this.StatusBar = new Gtk.Statusbar();
            this.StatusBar.Name = "StatusBar";
            this.StatusBar.Spacing = 6;
            // Container child StatusBar.Gtk.Box+BoxChild
            this.pbLoadStatus = new Gtk.ProgressBar();
            this.pbLoadStatus.Name = "pbLoadStatus";
            this.pbLoadStatus.Text = Mono.Unix.Catalog.GetString("Waiting...");
            this.StatusBar.Add(this.pbLoadStatus);
            Gtk.Box.BoxChild w15 = ((Gtk.Box.BoxChild)(this.StatusBar[this.pbLoadStatus]));
            w15.Position = 1;
            this.vbox4.Add(this.StatusBar);
            Gtk.Box.BoxChild w16 = ((Gtk.Box.BoxChild)(this.vbox4[this.StatusBar]));
            w16.PackType = ((Gtk.PackType)(1));
            w16.Position = 6;
            w16.Expand = false;
            w16.Fill = false;
            this.Add(this.vbox4);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 520;
            this.DefaultHeight = 300;
            this.Show();
            this.cmdOpen.Activated += new System.EventHandler(this.OnCmdOpenActivated);
            this.cmdSave.Activated += new System.EventHandler(this.OnCmdSaveActivated);
        }
    }
}
