// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace PubComb {
    
    
    public partial class SpamBlockFormGTK {
        
        private Gtk.VBox vbox5;
        
        private Gtk.Label lblCredits;
        
        private Gtk.HSeparator hseparator5;
        
        private Gtk.CheckButton chkDialog;
        
        private Gtk.CheckButton chkModRights;
        
        private Gtk.CheckButton chkIM;
        
        private Gtk.CheckButton chkSound;
        
        private Gtk.CheckButton chkMap;
        
        private Gtk.ScrolledWindow GtkScrolledWindow;
        
        private Gtk.TextView txtDebug;
        
        private Gtk.HSeparator hseparator6;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget PubComb.SpamBlockFormGTK
            this.Name = "PubComb.SpamBlockFormGTK";
            this.Title = Mono.Unix.Catalog.GetString("SpamBlockFormGTK");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            // Container child PubComb.SpamBlockFormGTK.Gtk.Container+ContainerChild
            this.vbox5 = new Gtk.VBox();
            this.vbox5.Name = "vbox5";
            this.vbox5.Spacing = 6;
            // Container child vbox5.Gtk.Box+BoxChild
            this.lblCredits = new Gtk.Label();
            this.lblCredits.Name = "lblCredits";
            this.lblCredits.LabelProp = Mono.Unix.Catalog.GetString("Plugin by LGG.");
            this.vbox5.Add(this.lblCredits);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.vbox5[this.lblCredits]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child vbox5.Gtk.Box+BoxChild
            this.hseparator5 = new Gtk.HSeparator();
            this.hseparator5.Name = "hseparator5";
            this.vbox5.Add(this.hseparator5);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox5[this.hseparator5]));
            w2.Position = 1;
            w2.Expand = false;
            w2.Fill = false;
            // Container child vbox5.Gtk.Box+BoxChild
            this.chkDialog = new Gtk.CheckButton();
            this.chkDialog.CanFocus = true;
            this.chkDialog.Name = "chkDialog";
            this.chkDialog.Label = Mono.Unix.Catalog.GetString("Block llDialog spam");
            this.chkDialog.Active = true;
            this.chkDialog.DrawIndicator = true;
            this.chkDialog.UseUnderline = true;
            this.vbox5.Add(this.chkDialog);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox5[this.chkDialog]));
            w3.Position = 2;
            w3.Expand = false;
            w3.Fill = false;
            // Container child vbox5.Gtk.Box+BoxChild
            this.chkModRights = new Gtk.CheckButton();
            this.chkModRights.CanFocus = true;
            this.chkModRights.Name = "chkModRights";
            this.chkModRights.Label = Mono.Unix.Catalog.GetString("Block Mod Rights spam");
            this.chkModRights.Active = true;
            this.chkModRights.DrawIndicator = true;
            this.chkModRights.UseUnderline = true;
            this.vbox5.Add(this.chkModRights);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.vbox5[this.chkModRights]));
            w4.Position = 3;
            w4.Expand = false;
            w4.Fill = false;
            // Container child vbox5.Gtk.Box+BoxChild
            this.chkIM = new Gtk.CheckButton();
            this.chkIM.CanFocus = true;
            this.chkIM.Name = "chkIM";
            this.chkIM.Label = Mono.Unix.Catalog.GetString("IM Spam (Includes inventory offers, friendship requests, and calling cards)");
            this.chkIM.Active = true;
            this.chkIM.DrawIndicator = true;
            this.chkIM.UseUnderline = true;
            this.vbox5.Add(this.chkIM);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.vbox5[this.chkIM]));
            w5.Position = 4;
            w5.Expand = false;
            w5.Fill = false;
            // Container child vbox5.Gtk.Box+BoxChild
            this.chkSound = new Gtk.CheckButton();
            this.chkSound.CanFocus = true;
            this.chkSound.Name = "chkSound";
            this.chkSound.Label = Mono.Unix.Catalog.GetString("Sound spam (can mess with gestures)");
            this.chkSound.DrawIndicator = true;
            this.chkSound.UseUnderline = true;
            this.vbox5.Add(this.chkSound);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.vbox5[this.chkSound]));
            w6.Position = 5;
            w6.Expand = false;
            w6.Fill = false;
            // Container child vbox5.Gtk.Box+BoxChild
            this.chkMap = new Gtk.CheckButton();
            this.chkMap.CanFocus = true;
            this.chkMap.Name = "chkMap";
            this.chkMap.Label = Mono.Unix.Catalog.GetString("Map request spam");
            this.chkMap.Active = true;
            this.chkMap.DrawIndicator = true;
            this.chkMap.UseUnderline = true;
            this.vbox5.Add(this.chkMap);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.vbox5[this.chkMap]));
            w7.Position = 6;
            w7.Expand = false;
            w7.Fill = false;
            // Container child vbox5.Gtk.Box+BoxChild
            this.GtkScrolledWindow = new Gtk.ScrolledWindow();
            this.GtkScrolledWindow.Name = "GtkScrolledWindow";
            this.GtkScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
            // Container child GtkScrolledWindow.Gtk.Container+ContainerChild
            this.txtDebug = new Gtk.TextView();
            this.txtDebug.CanFocus = true;
            this.txtDebug.Name = "txtDebug";
            this.txtDebug.Editable = false;
            this.GtkScrolledWindow.Add(this.txtDebug);
            this.vbox5.Add(this.GtkScrolledWindow);
            Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.vbox5[this.GtkScrolledWindow]));
            w9.PackType = ((Gtk.PackType)(1));
            w9.Position = 7;
            // Container child vbox5.Gtk.Box+BoxChild
            this.hseparator6 = new Gtk.HSeparator();
            this.hseparator6.Name = "hseparator6";
            this.vbox5.Add(this.hseparator6);
            Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.vbox5[this.hseparator6]));
            w10.PackType = ((Gtk.PackType)(1));
            w10.Position = 8;
            w10.Expand = false;
            w10.Fill = false;
            this.Add(this.vbox5);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 507;
            this.DefaultHeight = 300;
            this.Show();
            this.chkSound.Toggled += new System.EventHandler(this.OnChkSoundToggled);
        }
    }
}
