// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace PubComb {
    
    
    public partial class LyraFormGTK {
        
        private Gtk.VBox vbox6;
        
        private Gtk.Label lblTitle;
        
        private Gtk.HSeparator hseparator1;
        
        private Gtk.CheckButton chkEnabled;
        
        private Gtk.HBox hbox2;
        
        private Gtk.Label lblChatTrig;
        
        private Gtk.Entry txtChatTrig;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget PubComb.LyraFormGTK
            this.Name = "PubComb.LyraFormGTK";
            this.Title = Mono.Unix.Catalog.GetString("Lyra - Phantom Movelock");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            // Container child PubComb.LyraFormGTK.Gtk.Container+ContainerChild
            this.vbox6 = new Gtk.VBox();
            this.vbox6.Name = "vbox6";
            this.vbox6.Spacing = 6;
            // Container child vbox6.Gtk.Box+BoxChild
            this.lblTitle = new Gtk.Label();
            this.lblTitle.Name = "lblTitle";
            this.lblTitle.LabelProp = Mono.Unix.Catalog.GetString("<b>Lyra</b>\n\nPlugin by LGG, thanks to Day Oh for Teqnique");
            this.lblTitle.UseMarkup = true;
            this.lblTitle.Justify = ((Gtk.Justification)(2));
            this.vbox6.Add(this.lblTitle);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.vbox6[this.lblTitle]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child vbox6.Gtk.Box+BoxChild
            this.hseparator1 = new Gtk.HSeparator();
            this.hseparator1.Name = "hseparator1";
            this.vbox6.Add(this.hseparator1);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox6[this.hseparator1]));
            w2.Position = 1;
            w2.Expand = false;
            w2.Fill = false;
            // Container child vbox6.Gtk.Box+BoxChild
            this.chkEnabled = new Gtk.CheckButton();
            this.chkEnabled.CanFocus = true;
            this.chkEnabled.Name = "chkEnabled";
            this.chkEnabled.Label = Mono.Unix.Catalog.GetString("Enable Phantom Lock");
            this.chkEnabled.DrawIndicator = true;
            this.chkEnabled.UseUnderline = true;
            this.vbox6.Add(this.chkEnabled);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox6[this.chkEnabled]));
            w3.Position = 2;
            w3.Expand = false;
            w3.Fill = false;
            // Container child vbox6.Gtk.Box+BoxChild
            this.hbox2 = new Gtk.HBox();
            this.hbox2.Name = "hbox2";
            this.hbox2.Spacing = 6;
            // Container child hbox2.Gtk.Box+BoxChild
            this.lblChatTrig = new Gtk.Label();
            this.lblChatTrig.Name = "lblChatTrig";
            this.lblChatTrig.LabelProp = Mono.Unix.Catalog.GetString("Chat trigger to toggle phantom:");
            this.hbox2.Add(this.lblChatTrig);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.hbox2[this.lblChatTrig]));
            w4.Position = 0;
            w4.Expand = false;
            w4.Fill = false;
            // Container child hbox2.Gtk.Box+BoxChild
            this.txtChatTrig = new Gtk.Entry();
            this.txtChatTrig.CanFocus = true;
            this.txtChatTrig.Name = "txtChatTrig";
            this.txtChatTrig.IsEditable = true;
            this.txtChatTrig.InvisibleChar = '●';
            this.hbox2.Add(this.txtChatTrig);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.hbox2[this.txtChatTrig]));
            w5.Position = 1;
            this.vbox6.Add(this.hbox2);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.vbox6[this.hbox2]));
            w6.Position = 3;
            w6.Expand = false;
            w6.Fill = false;
            this.Add(this.vbox6);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 400;
            this.DefaultHeight = 300;
            this.Show();
            this.chkEnabled.Clicked += new System.EventHandler(this.OnChkEnabledClicked);
            this.txtChatTrig.Changed += new System.EventHandler(this.OnTxtChatTrigChanged);
        }
    }
}
