// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace PubComb {
    
    
    public partial class RainbowParticlesFormGTK {
        
        private Gtk.VBox vbox1;
        
        private Gtk.Label lblTitle;
        
        private Gtk.HSeparator hseparator1;
        
        private Gtk.HBox hbox1;
        
        private Gtk.Label lblBeamType;
        
        private Gtk.ComboBox cboBeamtype;
        
        private Gtk.HSeparator hseparator2;
        
        private Gtk.HBox hbox3;
        
        private Gtk.ComboBox cboColors;
        
        private Gtk.Button cmdAddColor;
        
        private Gtk.HBox hbox2;
        
        private Gtk.ScrolledWindow GtkScrolledWindow;
        
        private Gtk.NodeView nodColors;
        
        private Gtk.VButtonBox butColors;
        
        private Gtk.Button cmdRemove;
        
        private Gtk.Button cmdMoveUp;
        
        private Gtk.Button cmdMoveDown;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget PubComb.RainbowParticlesFormGTK
            this.Name = "PubComb.RainbowParticlesFormGTK";
            this.Title = Mono.Unix.Catalog.GetString("RainbowParticlesFormGTK");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            // Container child PubComb.RainbowParticlesFormGTK.Gtk.Container+ContainerChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            this.lblTitle = new Gtk.Label();
            this.lblTitle.Name = "lblTitle";
            this.lblTitle.LabelProp = Mono.Unix.Catalog.GetString("Plugin by LGG and Day Oh.\nGUI Facelift by Fred.");
            this.lblTitle.Justify = ((Gtk.Justification)(2));
            this.vbox1.Add(this.lblTitle);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.vbox1[this.lblTitle]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hseparator1 = new Gtk.HSeparator();
            this.hseparator1.Name = "hseparator1";
            this.vbox1.Add(this.hseparator1);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox1[this.hseparator1]));
            w2.Position = 1;
            w2.Expand = false;
            w2.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.lblBeamType = new Gtk.Label();
            this.lblBeamType.Name = "lblBeamType";
            this.lblBeamType.LabelProp = Mono.Unix.Catalog.GetString("Type of Beam:");
            this.hbox1.Add(this.lblBeamType);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.hbox1[this.lblBeamType]));
            w3.Position = 0;
            w3.Expand = false;
            w3.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.cboBeamtype = Gtk.ComboBox.NewText();
            this.cboBeamtype.AppendText(Mono.Unix.Catalog.GetString("Leave my particles alone"));
            this.cboBeamtype.AppendText(Mono.Unix.Catalog.GetString("Spinning Circle Beam"));
            this.cboBeamtype.AppendText(Mono.Unix.Catalog.GetString("Quad Beams"));
            this.cboBeamtype.AppendText(Mono.Unix.Catalog.GetString("Single Color Change Beam"));
            this.cboBeamtype.AppendText(Mono.Unix.Catalog.GetString("SL Particle Beam"));
            this.cboBeamtype.Name = "cboBeamtype";
            this.cboBeamtype.Active = 0;
            this.hbox1.Add(this.cboBeamtype);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.hbox1[this.cboBeamtype]));
            w4.Position = 1;
            w4.Expand = false;
            w4.Fill = false;
            this.vbox1.Add(this.hbox1);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
            w5.Position = 2;
            w5.Expand = false;
            w5.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hseparator2 = new Gtk.HSeparator();
            this.hseparator2.Name = "hseparator2";
            this.vbox1.Add(this.hseparator2);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.vbox1[this.hseparator2]));
            w6.Position = 3;
            w6.Expand = false;
            w6.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbox3 = new Gtk.HBox();
            this.hbox3.Name = "hbox3";
            this.hbox3.Spacing = 8;
            // Container child hbox3.Gtk.Box+BoxChild
            this.cboColors = Gtk.ComboBox.NewText();
            this.cboColors.AppendText(Mono.Unix.Catalog.GetString("Red"));
            this.cboColors.AppendText(Mono.Unix.Catalog.GetString("Orange"));
            this.cboColors.AppendText(Mono.Unix.Catalog.GetString("Yellow"));
            this.cboColors.AppendText(Mono.Unix.Catalog.GetString("Lime"));
            this.cboColors.AppendText(Mono.Unix.Catalog.GetString("Green"));
            this.cboColors.AppendText(Mono.Unix.Catalog.GetString("Turquoise"));
            this.cboColors.AppendText(Mono.Unix.Catalog.GetString("Blue"));
            this.cboColors.AppendText(Mono.Unix.Catalog.GetString("Purple"));
            this.cboColors.AppendText(Mono.Unix.Catalog.GetString("Pink"));
            this.cboColors.AppendText(Mono.Unix.Catalog.GetString("Black"));
            this.cboColors.AppendText(Mono.Unix.Catalog.GetString("White"));
            this.cboColors.Name = "cboColors";
            this.cboColors.Active = 0;
            this.hbox3.Add(this.cboColors);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.hbox3[this.cboColors]));
            w7.Position = 0;
            w7.Expand = false;
            w7.Fill = false;
            // Container child hbox3.Gtk.Box+BoxChild
            this.cmdAddColor = new Gtk.Button();
            this.cmdAddColor.CanFocus = true;
            this.cmdAddColor.Name = "cmdAddColor";
            this.cmdAddColor.UseUnderline = true;
            this.cmdAddColor.Label = Mono.Unix.Catalog.GetString("Add Color");
            this.hbox3.Add(this.cmdAddColor);
            Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.hbox3[this.cmdAddColor]));
            w8.Position = 1;
            w8.Expand = false;
            w8.Fill = false;
            this.vbox1.Add(this.hbox3);
            Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox3]));
            w9.Position = 4;
            w9.Expand = false;
            w9.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbox2 = new Gtk.HBox();
            this.hbox2.Name = "hbox2";
            this.hbox2.Spacing = 6;
            // Container child hbox2.Gtk.Box+BoxChild
            this.GtkScrolledWindow = new Gtk.ScrolledWindow();
            this.GtkScrolledWindow.Name = "GtkScrolledWindow";
            this.GtkScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
            // Container child GtkScrolledWindow.Gtk.Container+ContainerChild
            this.nodColors = new Gtk.NodeView();
            this.nodColors.CanFocus = true;
            this.nodColors.Name = "nodColors";
            this.GtkScrolledWindow.Add(this.nodColors);
            this.hbox2.Add(this.GtkScrolledWindow);
            Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(this.hbox2[this.GtkScrolledWindow]));
            w11.Position = 0;
            // Container child hbox2.Gtk.Box+BoxChild
            this.butColors = new Gtk.VButtonBox();
            this.butColors.Name = "butColors";
            this.butColors.LayoutStyle = ((Gtk.ButtonBoxStyle)(3));
            // Container child butColors.Gtk.ButtonBox+ButtonBoxChild
            this.cmdRemove = new Gtk.Button();
            this.cmdRemove.CanFocus = true;
            this.cmdRemove.Name = "cmdRemove";
            this.cmdRemove.UseUnderline = true;
            this.cmdRemove.Label = Mono.Unix.Catalog.GetString("Remove");
            this.butColors.Add(this.cmdRemove);
            Gtk.ButtonBox.ButtonBoxChild w12 = ((Gtk.ButtonBox.ButtonBoxChild)(this.butColors[this.cmdRemove]));
            w12.Expand = false;
            w12.Fill = false;
            // Container child butColors.Gtk.ButtonBox+ButtonBoxChild
            this.cmdMoveUp = new Gtk.Button();
            this.cmdMoveUp.CanFocus = true;
            this.cmdMoveUp.Name = "cmdMoveUp";
            this.cmdMoveUp.UseUnderline = true;
            this.cmdMoveUp.Label = Mono.Unix.Catalog.GetString("Move Up");
            this.butColors.Add(this.cmdMoveUp);
            Gtk.ButtonBox.ButtonBoxChild w13 = ((Gtk.ButtonBox.ButtonBoxChild)(this.butColors[this.cmdMoveUp]));
            w13.Position = 1;
            w13.Expand = false;
            w13.Fill = false;
            // Container child butColors.Gtk.ButtonBox+ButtonBoxChild
            this.cmdMoveDown = new Gtk.Button();
            this.cmdMoveDown.CanFocus = true;
            this.cmdMoveDown.Name = "cmdMoveDown";
            this.cmdMoveDown.UseUnderline = true;
            this.cmdMoveDown.Label = Mono.Unix.Catalog.GetString("Move Down");
            this.butColors.Add(this.cmdMoveDown);
            Gtk.ButtonBox.ButtonBoxChild w14 = ((Gtk.ButtonBox.ButtonBoxChild)(this.butColors[this.cmdMoveDown]));
            w14.Position = 2;
            w14.Expand = false;
            w14.Fill = false;
            this.hbox2.Add(this.butColors);
            Gtk.Box.BoxChild w15 = ((Gtk.Box.BoxChild)(this.hbox2[this.butColors]));
            w15.Position = 1;
            w15.Expand = false;
            w15.Fill = false;
            this.vbox1.Add(this.hbox2);
            Gtk.Box.BoxChild w16 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
            w16.Position = 5;
            this.Add(this.vbox1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 400;
            this.DefaultHeight = 300;
            this.Show();
            this.cboBeamtype.Changed += new System.EventHandler(this.OnCboBeamtypeChanged);
            this.cmdAddColor.Activated += new System.EventHandler(this.OnCmdAddColorActivated);
            this.cmdRemove.Activated += new System.EventHandler(this.OnCmdRemoveActivated);
            this.cmdMoveUp.Activated += new System.EventHandler(this.OnCmdMoveUpActivated);
            this.cmdMoveDown.Activated += new System.EventHandler(this.OnCmdMoveDownActivated);
        }
    }
}
