// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace PubComb {
    
    
    public partial class LeetFormGTK {
        
        private Gtk.VBox vbox2;
        
        private Gtk.Label lblTitle;
        
        private Gtk.CheckButton chkEnabled;
        
        private Gtk.ComboBox cboLevel;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget PubComb.LeetFormGTK
            this.Name = "PubComb.LeetFormGTK";
            this.Title = Mono.Unix.Catalog.GetString("LeetFormGTK");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            // Container child PubComb.LeetFormGTK.Gtk.Container+ContainerChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.lblTitle = new Gtk.Label();
            this.lblTitle.Name = "lblTitle";
            this.lblTitle.Xpad = 3;
            this.lblTitle.LabelProp = Mono.Unix.Catalog.GetString("1337 Encoder/Decoder\n\nPlugin by LordGregGreg Back");
            this.lblTitle.Justify = ((Gtk.Justification)(2));
            this.vbox2.Add(this.lblTitle);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.vbox2[this.lblTitle]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.chkEnabled = new Gtk.CheckButton();
            this.chkEnabled.CanFocus = true;
            this.chkEnabled.Name = "chkEnabled";
            this.chkEnabled.Label = Mono.Unix.Catalog.GetString("Enable 1337 plugin");
            this.chkEnabled.DrawIndicator = true;
            this.chkEnabled.UseUnderline = true;
            this.vbox2.Add(this.chkEnabled);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox2[this.chkEnabled]));
            w2.Position = 1;
            w2.Expand = false;
            w2.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.cboLevel = Gtk.ComboBox.NewText();
            this.cboLevel.AppendText(Mono.Unix.Catalog.GetString("Leet Off\r"));
            this.cboLevel.AppendText(Mono.Unix.Catalog.GetString("LeetLevel 1\r"));
            this.cboLevel.AppendText(Mono.Unix.Catalog.GetString("LeetLevel 2\r"));
            this.cboLevel.AppendText(Mono.Unix.Catalog.GetString("LeetLevel 3\r"));
            this.cboLevel.AppendText(Mono.Unix.Catalog.GetString("LeetLevel 4\r"));
            this.cboLevel.AppendText(Mono.Unix.Catalog.GetString("LeetLevel 5\r"));
            this.cboLevel.AppendText(Mono.Unix.Catalog.GetString("LeetLevel 6\r"));
            this.cboLevel.AppendText(Mono.Unix.Catalog.GetString("LeetLevel 7\r"));
            this.cboLevel.AppendText(Mono.Unix.Catalog.GetString("LeetLevel 8\r"));
            this.cboLevel.AppendText(Mono.Unix.Catalog.GetString("LeetLevel 9"));
            this.cboLevel.Name = "cboLevel";
            this.cboLevel.Active = 0;
            this.vbox2.Add(this.cboLevel);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox2[this.cboLevel]));
            w3.Position = 2;
            w3.Expand = false;
            w3.Fill = false;
            this.Add(this.vbox2);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 400;
            this.DefaultHeight = 300;
            this.Show();
        }
    }
}
