// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace PubComb {
    
    
    public partial class CapsFormGTK {
        
        private Gtk.VBox vbox2;
        
        private Gtk.Label lblTitle;
        
        private Gtk.HSeparator hseparator2;
        
        private Gtk.HBox hbox1;
        
        private Gtk.ScrolledWindow GtkScrolledWindow;
        
        private Gtk.TreeView nodEnabled;
        
        private Gtk.ScrolledWindow GtkScrolledWindow1;
        
        private Gtk.TreeView nodDisabled;
        
        private Gtk.HButtonBox hbuttonbox1;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget PubComb.CapsFormGTK
            this.Name = "PubComb.CapsFormGTK";
            this.Title = Mono.Unix.Catalog.GetString("CapsFormGTK");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            // Container child PubComb.CapsFormGTK.Gtk.Container+ContainerChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            this.vbox2.BorderWidth = ((uint)(3));
            // Container child vbox2.Gtk.Box+BoxChild
            this.lblTitle = new Gtk.Label();
            this.lblTitle.Name = "lblTitle";
            this.lblTitle.LabelProp = Mono.Unix.Catalog.GetString("Plugin by LGG\n\n<b>ADVANCED USE ONLY, YOU COULD ROYALLY SCREW UP YOUR GAME.</b>\n\nDoubleclick to enable/disable a capability.");
            this.lblTitle.UseMarkup = true;
            this.lblTitle.Justify = ((Gtk.Justification)(2));
            this.vbox2.Add(this.lblTitle);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.vbox2[this.lblTitle]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.hseparator2 = new Gtk.HSeparator();
            this.hseparator2.Name = "hseparator2";
            this.vbox2.Add(this.hseparator2);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox2[this.hseparator2]));
            w2.Position = 1;
            w2.Expand = false;
            w2.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.GtkScrolledWindow = new Gtk.ScrolledWindow();
            this.GtkScrolledWindow.Name = "GtkScrolledWindow";
            this.GtkScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
            // Container child GtkScrolledWindow.Gtk.Container+ContainerChild
            this.nodEnabled = new Gtk.TreeView();
            this.nodEnabled.CanFocus = true;
            this.nodEnabled.Name = "nodEnabled";
            this.GtkScrolledWindow.Add(this.nodEnabled);
            this.hbox1.Add(this.GtkScrolledWindow);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.hbox1[this.GtkScrolledWindow]));
            w4.Position = 0;
            // Container child hbox1.Gtk.Box+BoxChild
            this.GtkScrolledWindow1 = new Gtk.ScrolledWindow();
            this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
            this.GtkScrolledWindow1.ShadowType = ((Gtk.ShadowType)(1));
            // Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
            this.nodDisabled = new Gtk.TreeView();
            this.nodDisabled.CanFocus = true;
            this.nodDisabled.Name = "nodDisabled";
            this.GtkScrolledWindow1.Add(this.nodDisabled);
            this.hbox1.Add(this.GtkScrolledWindow1);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.hbox1[this.GtkScrolledWindow1]));
            w6.Position = 1;
            this.vbox2.Add(this.hbox1);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
            w7.Position = 2;
            // Container child vbox2.Gtk.Box+BoxChild
            this.hbuttonbox1 = new Gtk.HButtonBox();
            this.hbuttonbox1.Name = "hbuttonbox1";
            this.hbuttonbox1.LayoutStyle = ((Gtk.ButtonBoxStyle)(1));
            this.vbox2.Add(this.hbuttonbox1);
            Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbuttonbox1]));
            w8.Position = 3;
            w8.Expand = false;
            w8.Fill = false;
            this.Add(this.vbox2);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 519;
            this.DefaultHeight = 355;
            this.Show();
            this.nodEnabled.RowActivated += new Gtk.RowActivatedHandler(this.OnNodEnabledRowActivated);
            this.nodDisabled.RowActivated += new Gtk.RowActivatedHandler(this.OnNodDisabledRowActivated);
        }
    }
}
