// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace LSLObf {
    
    
    public partial class MainFormGTK {
        
        private Gtk.UIManager UIManager;
        
        private Gtk.Action FileAction;
        
        private Gtk.ToggleAction EnableObfuscationLslobfAction;
        
        private Gtk.Action QuitAction;
        
        private Gtk.Action HelpAction;
        
        private Gtk.Action AboutAction;
        
        private Gtk.Action HelpAction1;
        
        private Gtk.Action SettingsAction;
        
        private Gtk.Action ObfuscationSettingsMenuAction;
        
        private Gtk.VBox vbox2;
        
        private Gtk.MenuBar menubar1;
        
        private Gtk.Frame frmOldCode;
        
        private Gtk.Alignment GtkAlignment;
        
        private Gtk.ScrolledWindow GtkScrolledWindow;
        
        private Gtk.TextView txtOriginal;
        
        private Gtk.Label lslOldCode;
        
        private Gtk.Frame frmNewCode;
        
        private Gtk.Alignment GtkAlignment1;
        
        private Gtk.ScrolledWindow scrolledwindow1;
        
        private Gtk.TextView txtObfuscated;
        
        private Gtk.Label lblNewCode;
        
        private Gtk.Button cmdObfuscate;
        
        private Gtk.Statusbar sbMain;
        
        private Gtk.ProgressBar pbProgress;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget LSLObf.MainFormGTK
            this.UIManager = new Gtk.UIManager();
            Gtk.ActionGroup w1 = new Gtk.ActionGroup("Default");
            this.FileAction = new Gtk.Action("FileAction", Mono.Unix.Catalog.GetString("_File"), null, null);
            this.FileAction.ShortLabel = Mono.Unix.Catalog.GetString("_File");
            w1.Add(this.FileAction, null);
            this.EnableObfuscationLslobfAction = new Gtk.ToggleAction("EnableObfuscationLslobfAction", Mono.Unix.Catalog.GetString("Enable Obfuscation (/lslobf)"), null, null);
            this.EnableObfuscationLslobfAction.ShortLabel = Mono.Unix.Catalog.GetString("Enable Obfuscation (/lslobf)");
            w1.Add(this.EnableObfuscationLslobfAction, null);
            this.QuitAction = new Gtk.Action("QuitAction", Mono.Unix.Catalog.GetString("_Quit"), null, "gtk-quit");
            this.QuitAction.ShortLabel = Mono.Unix.Catalog.GetString("_Quit");
            w1.Add(this.QuitAction, null);
            this.HelpAction = new Gtk.Action("HelpAction", Mono.Unix.Catalog.GetString("Help"), null, null);
            this.HelpAction.ShortLabel = Mono.Unix.Catalog.GetString("Help");
            w1.Add(this.HelpAction, null);
            this.AboutAction = new Gtk.Action("AboutAction", Mono.Unix.Catalog.GetString("_About"), null, null);
            this.AboutAction.ShortLabel = Mono.Unix.Catalog.GetString("_About");
            w1.Add(this.AboutAction, null);
            this.HelpAction1 = new Gtk.Action("HelpAction1", Mono.Unix.Catalog.GetString("_Help"), null, null);
            this.HelpAction1.ShortLabel = Mono.Unix.Catalog.GetString("_Help");
            w1.Add(this.HelpAction1, null);
            this.SettingsAction = new Gtk.Action("SettingsAction", Mono.Unix.Catalog.GetString("Settings"), null, null);
            this.SettingsAction.ShortLabel = Mono.Unix.Catalog.GetString("Settings");
            w1.Add(this.SettingsAction, null);
            this.ObfuscationSettingsMenuAction = new Gtk.Action("ObfuscationSettingsMenuAction", Mono.Unix.Catalog.GetString("Obfuscation settings menu"), null, "gtk-preferences");
            this.ObfuscationSettingsMenuAction.ShortLabel = Mono.Unix.Catalog.GetString("Obfuscation settings menu");
            w1.Add(this.ObfuscationSettingsMenuAction, null);
            this.UIManager.InsertActionGroup(w1, 0);
            this.AddAccelGroup(this.UIManager.AccelGroup);
            this.Name = "LSLObf.MainFormGTK";
            this.Title = Mono.Unix.Catalog.GetString("LSL Obfuscator");
            this.WindowPosition = ((Gtk.WindowPosition)(3));
            this.BorderWidth = ((uint)(3));
            // Container child LSLObf.MainFormGTK.Gtk.Container+ContainerChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.UIManager.AddUiFromString("<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'><menuitem name='EnableObfuscationLslobfAction' action='EnableObfuscationLslobfAction'/><menuitem name='QuitAction' action='QuitAction'/></menu><menu name='SettingsAction' action='SettingsAction'><menuitem name='ObfuscationSettingsMenuAction' action='ObfuscationSettingsMenuAction'/></menu><menu name='HelpAction' action='HelpAction'><menuitem name='AboutAction' action='AboutAction'/><menuitem name='HelpAction1' action='HelpAction1'/></menu></menubar></ui>");
            this.menubar1 = ((Gtk.MenuBar)(this.UIManager.GetWidget("/menubar1")));
            this.menubar1.Name = "menubar1";
            this.vbox2.Add(this.menubar1);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox2[this.menubar1]));
            w2.Position = 0;
            w2.Expand = false;
            w2.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.frmOldCode = new Gtk.Frame();
            this.frmOldCode.Name = "frmOldCode";
            this.frmOldCode.ShadowType = ((Gtk.ShadowType)(0));
            // Container child frmOldCode.Gtk.Container+ContainerChild
            this.GtkAlignment = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment.Name = "GtkAlignment";
            this.GtkAlignment.LeftPadding = ((uint)(12));
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            this.GtkScrolledWindow = new Gtk.ScrolledWindow();
            this.GtkScrolledWindow.Name = "GtkScrolledWindow";
            this.GtkScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
            // Container child GtkScrolledWindow.Gtk.Container+ContainerChild
            this.txtOriginal = new Gtk.TextView();
            this.txtOriginal.CanFocus = true;
            this.txtOriginal.Name = "txtOriginal";
            this.GtkScrolledWindow.Add(this.txtOriginal);
            this.GtkAlignment.Add(this.GtkScrolledWindow);
            this.frmOldCode.Add(this.GtkAlignment);
            this.lslOldCode = new Gtk.Label();
            this.lslOldCode.Name = "lslOldCode";
            this.lslOldCode.LabelProp = Mono.Unix.Catalog.GetString("<b>Old (Unobfuscated) Code</b>");
            this.lslOldCode.UseMarkup = true;
            this.frmOldCode.LabelWidget = this.lslOldCode;
            this.vbox2.Add(this.frmOldCode);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.vbox2[this.frmOldCode]));
            w6.Position = 1;
            // Container child vbox2.Gtk.Box+BoxChild
            this.frmNewCode = new Gtk.Frame();
            this.frmNewCode.Name = "frmNewCode";
            this.frmNewCode.ShadowType = ((Gtk.ShadowType)(0));
            // Container child frmNewCode.Gtk.Container+ContainerChild
            this.GtkAlignment1 = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment1.Name = "GtkAlignment1";
            this.GtkAlignment1.LeftPadding = ((uint)(12));
            // Container child GtkAlignment1.Gtk.Container+ContainerChild
            this.scrolledwindow1 = new Gtk.ScrolledWindow();
            this.scrolledwindow1.CanFocus = true;
            this.scrolledwindow1.Name = "scrolledwindow1";
            this.scrolledwindow1.ShadowType = ((Gtk.ShadowType)(1));
            // Container child scrolledwindow1.Gtk.Container+ContainerChild
            this.txtObfuscated = new Gtk.TextView();
            this.txtObfuscated.CanFocus = true;
            this.txtObfuscated.Name = "txtObfuscated";
            this.txtObfuscated.Editable = false;
            this.scrolledwindow1.Add(this.txtObfuscated);
            this.GtkAlignment1.Add(this.scrolledwindow1);
            this.frmNewCode.Add(this.GtkAlignment1);
            this.lblNewCode = new Gtk.Label();
            this.lblNewCode.Name = "lblNewCode";
            this.lblNewCode.LabelProp = Mono.Unix.Catalog.GetString("<b>Obfuscated Code</b>");
            this.lblNewCode.UseMarkup = true;
            this.frmNewCode.LabelWidget = this.lblNewCode;
            this.vbox2.Add(this.frmNewCode);
            Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.vbox2[this.frmNewCode]));
            w10.Position = 2;
            // Container child vbox2.Gtk.Box+BoxChild
            this.cmdObfuscate = new Gtk.Button();
            this.cmdObfuscate.CanFocus = true;
            this.cmdObfuscate.Name = "cmdObfuscate";
            this.cmdObfuscate.UseStock = true;
            this.cmdObfuscate.UseUnderline = true;
            this.cmdObfuscate.Label = "gtk-execute";
            this.vbox2.Add(this.cmdObfuscate);
            Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(this.vbox2[this.cmdObfuscate]));
            w11.Position = 3;
            w11.Expand = false;
            w11.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.sbMain = new Gtk.Statusbar();
            this.sbMain.Name = "sbMain";
            this.sbMain.Spacing = 6;
            // Container child sbMain.Gtk.Box+BoxChild
            this.pbProgress = new Gtk.ProgressBar();
            this.pbProgress.Name = "pbProgress";
            this.pbProgress.Text = Mono.Unix.Catalog.GetString("Idle.");
            this.sbMain.Add(this.pbProgress);
            Gtk.Box.BoxChild w12 = ((Gtk.Box.BoxChild)(this.sbMain[this.pbProgress]));
            w12.Position = 1;
            this.vbox2.Add(this.sbMain);
            Gtk.Box.BoxChild w13 = ((Gtk.Box.BoxChild)(this.vbox2[this.sbMain]));
            w13.Position = 4;
            w13.Expand = false;
            w13.Fill = false;
            this.Add(this.vbox2);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 511;
            this.DefaultHeight = 322;
            this.Show();
        }
    }
}
