// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.UIManager UIManager;
    
    private Gtk.Action FileAction;
    
    private Gtk.Action ExitAction;
    
    private Gtk.Action actCancel;
    
    private Gtk.Action actLaunch;
    
    private Gtk.Action actEnable;
    
    private Gtk.Action actDisable;
    
    private Gtk.VBox vbox1;
    
    private Gtk.MenuBar menubar3;
    
    private Gtk.Toolbar toolbar1;
    
    private Gtk.HPaned hpaned1;
    
    private Gtk.ScrolledWindow GtkScrolledWindow;
    
    private Gtk.NodeView PluginList;
    
    private Gtk.ScrolledWindow GtkScrolledWindow1;
    
    private Gtk.Label lblPluginData;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize(this);
        // Widget MainWindow
        this.UIManager = new Gtk.UIManager();
        Gtk.ActionGroup w1 = new Gtk.ActionGroup("Default");
        this.FileAction = new Gtk.Action("FileAction", Mono.Unix.Catalog.GetString("_File"), null, null);
        this.FileAction.ShortLabel = Mono.Unix.Catalog.GetString("_File");
        w1.Add(this.FileAction, null);
        this.ExitAction = new Gtk.Action("ExitAction", Mono.Unix.Catalog.GetString("_Exit"), null, "gtk-cancel");
        this.ExitAction.ShortLabel = Mono.Unix.Catalog.GetString("_Exit");
        w1.Add(this.ExitAction, null);
        this.actCancel = new Gtk.Action("actCancel", null, null, "gtk-cancel");
        w1.Add(this.actCancel, null);
        this.actLaunch = new Gtk.Action("actLaunch", Mono.Unix.Catalog.GetString("_LAUNCH!"), null, "gtk-apply");
        this.actLaunch.ShortLabel = Mono.Unix.Catalog.GetString("_LAUNCH!");
        w1.Add(this.actLaunch, null);
        this.actEnable = new Gtk.Action("actEnable", Mono.Unix.Catalog.GetString("Enable Plugin"), null, "gtk-add");
        this.actEnable.ShortLabel = Mono.Unix.Catalog.GetString("Enable Plugin");
        w1.Add(this.actEnable, null);
        this.actDisable = new Gtk.Action("actDisable", Mono.Unix.Catalog.GetString("Disable"), null, "gtk-remove");
        this.actDisable.ShortLabel = Mono.Unix.Catalog.GetString("Disable");
        w1.Add(this.actDisable, null);
        this.UIManager.InsertActionGroup(w1, 0);
        this.AddAccelGroup(this.UIManager.AccelGroup);
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("PAR Loader for GTK");
        this.WindowPosition = ((Gtk.WindowPosition)(4));
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.vbox1 = new Gtk.VBox();
        this.vbox1.Name = "vbox1";
        this.vbox1.Spacing = 6;
        // Container child vbox1.Gtk.Box+BoxChild
        this.UIManager.AddUiFromString("<ui><menubar name='menubar3'><menu name='FileAction' action='FileAction'><menuitem name='ExitAction' action='ExitAction'/></menu></menubar></ui>");
        this.menubar3 = ((Gtk.MenuBar)(this.UIManager.GetWidget("/menubar3")));
        this.menubar3.Name = "menubar3";
        this.vbox1.Add(this.menubar3);
        Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox1[this.menubar3]));
        w2.Position = 0;
        w2.Expand = false;
        w2.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.UIManager.AddUiFromString("<ui><toolbar name='toolbar1'><toolitem name='actLaunch' action='actLaunch'/></toolbar></ui>");
        this.toolbar1 = ((Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar1")));
        this.toolbar1.Name = "toolbar1";
        this.toolbar1.ShowArrow = false;
        this.toolbar1.ToolbarStyle = ((Gtk.ToolbarStyle)(2));
        this.toolbar1.IconSize = ((Gtk.IconSize)(3));
        this.vbox1.Add(this.toolbar1);
        Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox1[this.toolbar1]));
        w3.Position = 1;
        w3.Expand = false;
        w3.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.hpaned1 = new Gtk.HPaned();
        this.hpaned1.CanFocus = true;
        this.hpaned1.Name = "hpaned1";
        this.hpaned1.Position = 160;
        // Container child hpaned1.Gtk.Paned+PanedChild
        this.GtkScrolledWindow = new Gtk.ScrolledWindow();
        this.GtkScrolledWindow.Name = "GtkScrolledWindow";
        this.GtkScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
        // Container child GtkScrolledWindow.Gtk.Container+ContainerChild
        this.PluginList = new Gtk.NodeView();
        this.PluginList.CanFocus = true;
        this.PluginList.Name = "PluginList";
        this.PluginList.Reorderable = true;
        this.GtkScrolledWindow.Add(this.PluginList);
        this.hpaned1.Add(this.GtkScrolledWindow);
        Gtk.Paned.PanedChild w5 = ((Gtk.Paned.PanedChild)(this.hpaned1[this.GtkScrolledWindow]));
        w5.Resize = false;
        // Container child hpaned1.Gtk.Paned+PanedChild
        this.GtkScrolledWindow1 = new Gtk.ScrolledWindow();
        this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
        this.GtkScrolledWindow1.ShadowType = ((Gtk.ShadowType)(1));
        // Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
        Gtk.Viewport w6 = new Gtk.Viewport();
        w6.ShadowType = ((Gtk.ShadowType)(0));
        // Container child GtkViewport.Gtk.Container+ContainerChild
        this.lblPluginData = new Gtk.Label();
        this.lblPluginData.Name = "lblPluginData";
        this.lblPluginData.LabelProp = Mono.Unix.Catalog.GetString("Click a plugin to view its data here.");
        this.lblPluginData.UseMarkup = true;
        this.lblPluginData.Wrap = true;
        w6.Add(this.lblPluginData);
        this.GtkScrolledWindow1.Add(w6);
        this.hpaned1.Add(this.GtkScrolledWindow1);
        this.vbox1.Add(this.hpaned1);
        Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.vbox1[this.hpaned1]));
        w10.Position = 2;
        this.Add(this.vbox1);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 636;
        this.DefaultHeight = 408;
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
        this.ExitAction.Activated += new System.EventHandler(this.OnExit);
        this.actLaunch.Activated += new System.EventHandler(this.OnActLaunchActivated);
    }
}
