// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace PubComb {
    
    
    public partial class ShadowFormGTK {
        
        private Gtk.Notebook nbMain;
        
        private Gtk.VBox vbox6;
        
        private Gtk.ScrolledWindow swinChatLog;
        
        private Gtk.EventBox evtChatLog;
        
        private Gtk.Label lblChatLog;
        
        private Gtk.HBox hbox4;
        
        private Gtk.Button cmdSend;
        
        private Gtk.Entry entry1;
        
        private Gtk.Label lblChat;
        
        private Gtk.VBox vbox7;
        
        private Gtk.Frame frame1;
        
        private Gtk.Alignment GtkAlignment;
        
        private Gtk.VBox vbox8;
        
        private Gtk.CheckButton chkEnabled;
        
        private Gtk.Label lblFrame;
        
        private Gtk.HButtonBox hbuttonbox2;
        
        private Gtk.Button cmdOK;
        
        private Gtk.Button cmdRevert;
        
        private Gtk.Frame framDecr;
        
        private Gtk.Alignment GtkAlignment1;
        
        private Gtk.Table table1;
        
        private Gtk.Label label11;
        
        private Gtk.Label label8;
        
        private Gtk.Label lblBrand;
        
        private Gtk.Entry txtBrand;
        
        private Gtk.Entry txtKey;
        
        private Gtk.Entry txtTrigger;
        
        private Gtk.Label lblFrame2;
        
        private Gtk.Label lblOptions;
        
        private Gtk.ScrolledWindow scrolledwindow2;
        
        private Gtk.Label lblAbout;
        
        private Gtk.Label label13;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget PubComb.ShadowFormGTK
            this.Name = "PubComb.ShadowFormGTK";
            this.Title = Mono.Unix.Catalog.GetString("ShadowFormGTK");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            // Container child PubComb.ShadowFormGTK.Gtk.Container+ContainerChild
            this.nbMain = new Gtk.Notebook();
            this.nbMain.CanFocus = true;
            this.nbMain.Name = "nbMain";
            this.nbMain.CurrentPage = 2;
            // Container child nbMain.Gtk.Notebook+NotebookChild
            this.vbox6 = new Gtk.VBox();
            this.vbox6.Name = "vbox6";
            this.vbox6.Spacing = 6;
            this.vbox6.BorderWidth = ((uint)(3));
            // Container child vbox6.Gtk.Box+BoxChild
            this.swinChatLog = new Gtk.ScrolledWindow();
            this.swinChatLog.CanFocus = true;
            this.swinChatLog.Name = "swinChatLog";
            this.swinChatLog.ShadowType = ((Gtk.ShadowType)(1));
            // Container child swinChatLog.Gtk.Container+ContainerChild
            Gtk.Viewport w1 = new Gtk.Viewport();
            w1.ShadowType = ((Gtk.ShadowType)(0));
            // Container child GtkViewport.Gtk.Container+ContainerChild
            this.evtChatLog = new Gtk.EventBox();
            this.evtChatLog.Name = "evtChatLog";
            this.evtChatLog.BorderWidth = ((uint)(3));
            // Container child evtChatLog.Gtk.Container+ContainerChild
            this.lblChatLog = new Gtk.Label();
            this.lblChatLog.Name = "lblChatLog";
            this.lblChatLog.Xpad = 3;
            this.lblChatLog.Ypad = 3;
            this.lblChatLog.Xalign = 0F;
            this.lblChatLog.UseMarkup = true;
            this.lblChatLog.Wrap = true;
            this.lblChatLog.Selectable = true;
            this.lblChatLog.WidthChars = 50;
            this.evtChatLog.Add(this.lblChatLog);
            w1.Add(this.evtChatLog);
            this.swinChatLog.Add(w1);
            this.vbox6.Add(this.swinChatLog);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.vbox6[this.swinChatLog]));
            w5.Position = 0;
            // Container child vbox6.Gtk.Box+BoxChild
            this.hbox4 = new Gtk.HBox();
            this.hbox4.Name = "hbox4";
            this.hbox4.Spacing = 6;
            // Container child hbox4.Gtk.Box+BoxChild
            this.cmdSend = new Gtk.Button();
            this.cmdSend.CanFocus = true;
            this.cmdSend.Name = "cmdSend";
            this.cmdSend.UseUnderline = true;
            this.cmdSend.BorderWidth = ((uint)(3));
            this.cmdSend.Label = Mono.Unix.Catalog.GetString("Send");
            this.hbox4.Add(this.cmdSend);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.hbox4[this.cmdSend]));
            w6.Position = 0;
            w6.Expand = false;
            w6.Fill = false;
            // Container child hbox4.Gtk.Box+BoxChild
            this.entry1 = new Gtk.Entry();
            this.entry1.CanFocus = true;
            this.entry1.Name = "entry1";
            this.entry1.IsEditable = true;
            this.entry1.InvisibleChar = '●';
            this.hbox4.Add(this.entry1);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.hbox4[this.entry1]));
            w7.Position = 1;
            this.vbox6.Add(this.hbox4);
            Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.vbox6[this.hbox4]));
            w8.Position = 1;
            w8.Expand = false;
            w8.Fill = false;
            this.nbMain.Add(this.vbox6);
            // Notebook tab
            this.lblChat = new Gtk.Label();
            this.lblChat.Name = "lblChat";
            this.lblChat.LabelProp = Mono.Unix.Catalog.GetString("Chat");
            this.nbMain.SetTabLabel(this.vbox6, this.lblChat);
            this.lblChat.ShowAll();
            // Container child nbMain.Gtk.Notebook+NotebookChild
            this.vbox7 = new Gtk.VBox();
            this.vbox7.Name = "vbox7";
            this.vbox7.Spacing = 6;
            // Container child vbox7.Gtk.Box+BoxChild
            this.frame1 = new Gtk.Frame();
            this.frame1.Name = "frame1";
            this.frame1.ShadowType = ((Gtk.ShadowType)(0));
            // Container child frame1.Gtk.Container+ContainerChild
            this.GtkAlignment = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment.Name = "GtkAlignment";
            this.GtkAlignment.LeftPadding = ((uint)(12));
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            this.vbox8 = new Gtk.VBox();
            this.vbox8.Name = "vbox8";
            this.vbox8.Spacing = 6;
            // Container child vbox8.Gtk.Box+BoxChild
            this.chkEnabled = new Gtk.CheckButton();
            this.chkEnabled.CanFocus = true;
            this.chkEnabled.Name = "chkEnabled";
            this.chkEnabled.Label = Mono.Unix.Catalog.GetString("Enable Shadow Plugin");
            this.chkEnabled.Active = true;
            this.chkEnabled.DrawIndicator = true;
            this.chkEnabled.UseUnderline = true;
            this.vbox8.Add(this.chkEnabled);
            Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.vbox8[this.chkEnabled]));
            w10.Position = 0;
            w10.Expand = false;
            w10.Fill = false;
            this.GtkAlignment.Add(this.vbox8);
            this.frame1.Add(this.GtkAlignment);
            this.lblFrame = new Gtk.Label();
            this.lblFrame.Name = "lblFrame";
            this.lblFrame.LabelProp = Mono.Unix.Catalog.GetString("<b>The Basics</b>");
            this.lblFrame.UseMarkup = true;
            this.frame1.LabelWidget = this.lblFrame;
            this.vbox7.Add(this.frame1);
            Gtk.Box.BoxChild w13 = ((Gtk.Box.BoxChild)(this.vbox7[this.frame1]));
            w13.Position = 0;
            w13.Expand = false;
            w13.Fill = false;
            // Container child vbox7.Gtk.Box+BoxChild
            this.hbuttonbox2 = new Gtk.HButtonBox();
            this.hbuttonbox2.Name = "hbuttonbox2";
            this.hbuttonbox2.BorderWidth = ((uint)(3));
            this.hbuttonbox2.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
            this.cmdOK = new Gtk.Button();
            this.cmdOK.CanFocus = true;
            this.cmdOK.Name = "cmdOK";
            this.cmdOK.UseStock = true;
            this.cmdOK.UseUnderline = true;
            this.cmdOK.Label = "gtk-save";
            this.hbuttonbox2.Add(this.cmdOK);
            Gtk.ButtonBox.ButtonBoxChild w14 = ((Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2[this.cmdOK]));
            w14.Expand = false;
            w14.Fill = false;
            // Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
            this.cmdRevert = new Gtk.Button();
            this.cmdRevert.CanFocus = true;
            this.cmdRevert.Name = "cmdRevert";
            this.cmdRevert.UseStock = true;
            this.cmdRevert.UseUnderline = true;
            this.cmdRevert.Label = "gtk-cancel";
            this.hbuttonbox2.Add(this.cmdRevert);
            Gtk.ButtonBox.ButtonBoxChild w15 = ((Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2[this.cmdRevert]));
            w15.Position = 1;
            w15.Expand = false;
            w15.Fill = false;
            this.vbox7.Add(this.hbuttonbox2);
            Gtk.Box.BoxChild w16 = ((Gtk.Box.BoxChild)(this.vbox7[this.hbuttonbox2]));
            w16.PackType = ((Gtk.PackType)(1));
            w16.Position = 1;
            w16.Expand = false;
            w16.Fill = false;
            // Container child vbox7.Gtk.Box+BoxChild
            this.framDecr = new Gtk.Frame();
            this.framDecr.Name = "framDecr";
            this.framDecr.ShadowType = ((Gtk.ShadowType)(0));
            // Container child framDecr.Gtk.Container+ContainerChild
            this.GtkAlignment1 = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment1.Name = "GtkAlignment1";
            this.GtkAlignment1.LeftPadding = ((uint)(12));
            // Container child GtkAlignment1.Gtk.Container+ContainerChild
            this.table1 = new Gtk.Table(((uint)(3)), ((uint)(2)), false);
            this.table1.Name = "table1";
            this.table1.RowSpacing = ((uint)(6));
            this.table1.ColumnSpacing = ((uint)(6));
            // Container child table1.Gtk.Table+TableChild
            this.label11 = new Gtk.Label();
            this.label11.Name = "label11";
            this.label11.LabelProp = Mono.Unix.Catalog.GetString("Trigger:");
            this.table1.Add(this.label11);
            Gtk.Table.TableChild w17 = ((Gtk.Table.TableChild)(this.table1[this.label11]));
            w17.TopAttach = ((uint)(1));
            w17.BottomAttach = ((uint)(2));
            w17.XOptions = ((Gtk.AttachOptions)(4));
            w17.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label8 = new Gtk.Label();
            this.label8.Name = "label8";
            this.label8.LabelProp = Mono.Unix.Catalog.GetString("Decryption Key:");
            this.table1.Add(this.label8);
            Gtk.Table.TableChild w18 = ((Gtk.Table.TableChild)(this.table1[this.label8]));
            w18.TopAttach = ((uint)(2));
            w18.BottomAttach = ((uint)(3));
            w18.XOptions = ((Gtk.AttachOptions)(4));
            w18.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.lblBrand = new Gtk.Label();
            this.lblBrand.Name = "lblBrand";
            this.lblBrand.LabelProp = Mono.Unix.Catalog.GetString("Brand:");
            this.table1.Add(this.lblBrand);
            Gtk.Table.TableChild w19 = ((Gtk.Table.TableChild)(this.table1[this.lblBrand]));
            w19.XOptions = ((Gtk.AttachOptions)(4));
            w19.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.txtBrand = new Gtk.Entry();
            this.txtBrand.CanFocus = true;
            this.txtBrand.Name = "txtBrand";
            this.txtBrand.IsEditable = true;
            this.txtBrand.InvisibleChar = '●';
            this.table1.Add(this.txtBrand);
            Gtk.Table.TableChild w20 = ((Gtk.Table.TableChild)(this.table1[this.txtBrand]));
            w20.LeftAttach = ((uint)(1));
            w20.RightAttach = ((uint)(2));
            w20.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.txtKey = new Gtk.Entry();
            this.txtKey.CanFocus = true;
            this.txtKey.Name = "txtKey";
            this.txtKey.IsEditable = true;
            this.txtKey.InvisibleChar = '●';
            this.table1.Add(this.txtKey);
            Gtk.Table.TableChild w21 = ((Gtk.Table.TableChild)(this.table1[this.txtKey]));
            w21.TopAttach = ((uint)(2));
            w21.BottomAttach = ((uint)(3));
            w21.LeftAttach = ((uint)(1));
            w21.RightAttach = ((uint)(2));
            w21.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.txtTrigger = new Gtk.Entry();
            this.txtTrigger.CanFocus = true;
            this.txtTrigger.Name = "txtTrigger";
            this.txtTrigger.IsEditable = true;
            this.txtTrigger.InvisibleChar = '●';
            this.table1.Add(this.txtTrigger);
            Gtk.Table.TableChild w22 = ((Gtk.Table.TableChild)(this.table1[this.txtTrigger]));
            w22.TopAttach = ((uint)(1));
            w22.BottomAttach = ((uint)(2));
            w22.LeftAttach = ((uint)(1));
            w22.RightAttach = ((uint)(2));
            w22.YOptions = ((Gtk.AttachOptions)(4));
            this.GtkAlignment1.Add(this.table1);
            this.framDecr.Add(this.GtkAlignment1);
            this.lblFrame2 = new Gtk.Label();
            this.lblFrame2.Name = "lblFrame2";
            this.lblFrame2.LabelProp = Mono.Unix.Catalog.GetString("<b>Decryption Settings</b>");
            this.lblFrame2.UseMarkup = true;
            this.framDecr.LabelWidget = this.lblFrame2;
            this.vbox7.Add(this.framDecr);
            Gtk.Box.BoxChild w25 = ((Gtk.Box.BoxChild)(this.vbox7[this.framDecr]));
            w25.PackType = ((Gtk.PackType)(1));
            w25.Position = 2;
            w25.Expand = false;
            w25.Fill = false;
            this.nbMain.Add(this.vbox7);
            Gtk.Notebook.NotebookChild w26 = ((Gtk.Notebook.NotebookChild)(this.nbMain[this.vbox7]));
            w26.Position = 1;
            // Notebook tab
            this.lblOptions = new Gtk.Label();
            this.lblOptions.Name = "lblOptions";
            this.lblOptions.LabelProp = Mono.Unix.Catalog.GetString("Options");
            this.nbMain.SetTabLabel(this.vbox7, this.lblOptions);
            this.lblOptions.ShowAll();
            // Container child nbMain.Gtk.Notebook+NotebookChild
            this.scrolledwindow2 = new Gtk.ScrolledWindow();
            this.scrolledwindow2.CanFocus = true;
            this.scrolledwindow2.Name = "scrolledwindow2";
            this.scrolledwindow2.ShadowType = ((Gtk.ShadowType)(1));
            // Container child scrolledwindow2.Gtk.Container+ContainerChild
            Gtk.Viewport w27 = new Gtk.Viewport();
            w27.ShadowType = ((Gtk.ShadowType)(0));
            // Container child GtkViewport1.Gtk.Container+ContainerChild
            this.lblAbout = new Gtk.Label();
            this.lblAbout.Name = "lblAbout";
            this.lblAbout.LabelProp = Mono.Unix.Catalog.GetString("<b>About Shadow</b>\n\nThis program was made by LordGregGreg for the purpose of allowing secure communications in an insecure world.  \n\n<i>Rob Nelson (Goes by N3X15 or Fred Rookstown, depending on where you look) also recoded the entire GUI so it would work reliably on Mac and Linux.  Worship him.</i>\n\nMessages sent with this plugin are encrypted BEFORE they are sent from your computer and decrypted AFTER the client computer recives them, (and before the client displays them).  This makes it impossible for chat interception on any level.\n\nSpecial Thanks to \"Philip Linden\" (yeah, thats not his actual sl name) and the OpenMetaverse project, and all it's contributors.\n\nAlso special thanks to ManyMonkeys for implementing TwoFish, and also the inventors of TwoFish!\n\nIf you plan to decompile and use this code, that is fine.  But please leave this message and access to it intact, that is all I ask. :)\n\nGo to http://code.google.com/p/par/wiki/ShadowTutorial for more info.");
            this.lblAbout.UseMarkup = true;
            this.lblAbout.Wrap = true;
            this.lblAbout.Selectable = true;
            w27.Add(this.lblAbout);
            this.scrolledwindow2.Add(w27);
            this.nbMain.Add(this.scrolledwindow2);
            Gtk.Notebook.NotebookChild w30 = ((Gtk.Notebook.NotebookChild)(this.nbMain[this.scrolledwindow2]));
            w30.Position = 2;
            // Notebook tab
            this.label13 = new Gtk.Label();
            this.label13.Name = "label13";
            this.label13.LabelProp = Mono.Unix.Catalog.GetString("About");
            this.nbMain.SetTabLabel(this.scrolledwindow2, this.label13);
            this.label13.ShowAll();
            this.Add(this.nbMain);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 578;
            this.DefaultHeight = 401;
            this.Show();
            this.cmdOK.Activated += new System.EventHandler(this.OnCmdOKActivated);
            this.cmdRevert.Activated += new System.EventHandler(this.OnCmdRevertActivated);
        }
    }
}
